/**
 * Third-party dependency inventory (§47, §48).
 *
 * Collects every package shipped at runtime (editor web build + Android shell), records name,
 * version, licence, source and copyright text, and writes:
 *   THIRD_PARTY_NOTICES.md                         (repository)
 *   apps/editor/public/third-party-licenses.json   (Settings → About → Licenses)
 *
 * Fails if a runtime dependency has a licence that conflicts with closed-source distribution
 * or has no identifiable licence.
 */
import { execSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const ALLOWED = new Set(['MIT', 'Apache-2.0', 'BSD-2-Clause', 'BSD-3-Clause', 'ISC', '0BSD', 'Zlib', 'CC0-1.0', 'BlueOak-1.0.0', 'Unlicense']);
const WORKSPACES = ['@mythic-forge/editor', '@mythic-forge/android', '@mythic-forge/core', '@mythic-forge/platform', '@mythic-forge/renderer'];

interface LsNode {
  version?: string;
  dependencies?: Record<string, LsNode>;
}

function collect(): Map<string, string> {
  // All arguments are constants defined above (no user input reaches the shell).
  const command = ['npm ls --omit=dev --all --json', ...WORKSPACES.map((w) => `-w ${w}`)].join(' ');
  const out = execSync(command, { cwd: ROOT, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  const tree = JSON.parse(out) as LsNode;
  const found = new Map<string, string>();
  const walk = (deps: Record<string, LsNode> | undefined): void => {
    for (const [name, node] of Object.entries(deps ?? {})) {
      if (name.startsWith('@mythic-forge/')) {
        walk(node.dependencies);
        continue;
      }
      if (!node.version || found.has(name)) continue;
      found.set(name, node.version);
      walk(node.dependencies);
    }
  };
  walk(tree.dependencies);
  return found;
}

interface Notice {
  name: string;
  version: string;
  license: string;
  source: string;
  author: string;
  licenseText: string;
  usage: string;
}

const USAGE: Record<string, string> = {
  three: '3D rendering, model loading and export (WebGL 2)',
  preact: 'User interface',
  '@preact/signals': 'UI state',
  '@preact/signals-core': 'UI state',
  fflate: 'Zip compression for .mfpack project packages',
  '@capacitor/core': 'Android shell bridge',
  '@capacitor/android': 'Android shell',
  '@capacitor/app': 'Android lifecycle and back button',
  '@capacitor/filesystem': 'Android export files',
  '@capacitor/share': 'Android share sheet for exports',
};

function readNotice(name: string, version: string): Notice {
  const dir = join(ROOT, 'node_modules', ...name.split('/'));
  const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')) as {
    license?: string | { type?: string };
    repository?: string | { url?: string };
    homepage?: string;
    author?: string | { name?: string };
  };
  const license = typeof pkg.license === 'string' ? pkg.license : (pkg.license?.type ?? 'UNKNOWN');
  const repo = typeof pkg.repository === 'string' ? pkg.repository : (pkg.repository?.url ?? pkg.homepage ?? '');
  const author = typeof pkg.author === 'string' ? pkg.author : (pkg.author?.name ?? '');
  const licenseFile = readdirSync(dir).find((f) => /^(licen[sc]e|copying)(\.|$)/i.test(f));
  const licenseText = licenseFile ? readFileSync(join(dir, licenseFile), 'utf8').trim() : '';
  return {
    name,
    version,
    license,
    source: repo.replace(/^git\+/, '').replace(/\.git$/, ''),
    author,
    licenseText,
    usage: USAGE[name] ?? 'Transitive dependency',
  };
}

const isAllowed = (expr: string): boolean => {
  // Handles simple SPDX expressions like "(MIT OR Apache-2.0)".
  const parts = expr.replace(/[()]/g, '').split(/\s+OR\s+/);
  return parts.some((p) => p.split(/\s+AND\s+/).every((x) => ALLOWED.has(x.trim())));
};

const deps = collect();
const notices = [...deps].map(([name, version]) => readNotice(name, version)).sort((a, b) => a.name.localeCompare(b.name));
const problems = notices.filter((n) => !isAllowed(n.license) || !n.licenseText);

const md: string[] = [
  '# Third-Party Notices',
  '',
  'Mythic Forge includes the open-source software listed below. Mythic Forge itself is not open source;',
  'these components remain under their own licences, reproduced here as their licences require.',
  '',
  '_Generated by `npm run notices`. Do not edit by hand._',
  '',
  '| Package | Version | Licence | Used for |',
  '|---|---|---|---|',
  ...notices.map((n) => `| ${n.name} | ${n.version} | ${n.license} | ${n.usage} |`),
  '',
  '## Native components not covered by this file',
  '',
  '- **Android shell**: Gradle pulls AndroidX and other libraries (mostly Apache-2.0) through Capacitor.',
  '  Generate their notices with a Gradle licence plugin before a store release (see docs/android.md).',
  '- **Desktop shell (Tauri)**: Rust crates must be inventoried with `cargo about` before release (see docs/windows.md).',
  '- **System WebView / WebView2**: provided by the operating system, not redistributed.',
  '',
  '## Licence texts',
  '',
];
for (const n of notices) {
  md.push(`### ${n.name} ${n.version}`, '', `Licence: ${n.license}${n.source ? ` — ${n.source}` : ''}`, '', '```', n.licenseText || '(licence text not found in package)', '```', '');
}
writeFileSync(join(ROOT, 'THIRD_PARTY_NOTICES.md'), `${md.join('\n')}\n`);
const publicDir = join(ROOT, 'apps', 'editor', 'public');
if (existsSync(publicDir)) {
  writeFileSync(
    join(publicDir, 'third-party-licenses.json'),
    JSON.stringify({ generated: true, packages: notices.map(({ name, version, license, source, usage, licenseText }) => ({ name, version, license, source, usage, licenseText })) }),
  );
}
console.log(`[notices] ${notices.length} runtime packages: ${[...new Set(notices.map((n) => n.license))].join(', ')}`);
if (problems.length) {
  for (const p of problems) console.error(`  ✗ ${p.name}@${p.version}: licence "${p.license}"${p.licenseText ? '' : ' (no licence text found)'}`);
  console.error('Third-party licence check FAILED.');
  process.exit(1);
}
